apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: java-app-10
  description: java springboot app for users - named java-app-10
  annotations:
    github.com/project-slug: ben14132-01/java-app-10
    backstage.io/techdocs-ref: dir:.
    'jenkins.io/job-full-name': java/java-app-10
spec:
  type: service
  owner: development
  lifecycle: experimental 
